### ISSUE TITLE
update 3.0.0 > 3.1.2 Fail

### ISSUE THREAD

**Issue by kermus** [AlexVerrico/octoprint-stats#18]
hi!

the update fails and the following error is logged in plugin_softwareupdate_console.log
2020-11-11 17: 46: 35,112! ERROR: Package 'OctoPrint-Stats' requires a different Python: 2.7.16 not in '> = 3.6, <4' 

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
connectivity.connection_check: 9.9.9.9:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1200
env.hardware.ram: 917016576
env.os.bits: 32
env.os.id: linux
env.os.platform: linux2
env.plugins.pi_support.model: Raspberry Pi 3 Model B Rev 1.2
env.plugins.pi_support.octopi_version: 0.17.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 19.3.1
env.python.version: 2.7.16
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.0rc1
printer.firmware: Marlin 2.0.7.2 (Oct 17 2020

**Comment by AlexVerrico** [comment]
Hi @kermus 
The latest release is not compatible with python 2. You can either manually install a python 2 version (see the README file) or upgrade octoprint to python 3.
Cheers,
Alex.
