### ISSUE TITLE
Cannot find it in Plugin Manager, why?

### ISSUE THREAD

**Issue by ppetrov-dev** [AlexVerrico/octoprint-stats#19]
I cannot find the plugin in Plugin Manager, why?
![image](https://user-images.githubusercontent.com/11585634/99192989-aa369b00-277e-11eb-93dd-07da145463ab.png)

**Comment by AlexVerrico** [comment]
Hi @ppetrov-dev 
Most likely it is because you are using Python 2.
You can either install the plugin manually using the url in the plugin README, or you can upgrade to python 3: https://octoprint.org/blog/2020/09/10/upgrade-to-py3/
Cheers,
Alex
