### ISSUE TITLE
Won’t install

### ISSUE THREAD

**Issue by renegadecitizen** [AlexVerrico/octoprint-stats#20]
Can you please help me 
I can’t get it to install 
By URL

**Comment by AlexVerrico** [comment]
Hi @renegadecitizen 
To be able to help I'll need a bit more information.
To start with, what URL are you using? 
What error message are you getting?
And if you can upload your logs that would help too.
Cheers,
Alex.

**Comment by renegadecitizen** [comment]
How do you upload my logs?

**Comment by AlexVerrico** [comment]
See https://community.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299
The logs that will help me are `octoprint.log` and `plugin_pluginmanager_console.log`

**Comment by renegadecitizen** [comment]
No problem 😎 
How do I upload my logs?

**Comment by AlexVerrico** [comment]
https://stackoverflow.com/a/49952640

**Comment by flowent59** [comment]
Important! You may need to install the system package libatlas-base-dev for this plugin to work by running **sudo apt install libatlas-base-dev**

**Comment by renegadecitizen** [comment]
Ok thanks

**Comment by AlexVerrico** [comment]
@renegadecitizen have you solved your issue? if not, please upload your logs so that I can help you.

**Comment by renegadecitizen** [comment]
That’s ok I decided it’s not worth the trouble 
Thanks for your help though
