### ISSUE TITLE
Not update from 2.0.2...

### ISSUE THREAD

**Issue by bgiovanny** [AlexVerrico/octoprint-stats#21]
Updating, please wait.
++++++++++++++++++++++++++++++++++++
Now updating Printer Stats to v3.1.2
++++++++++++++++++++++++++++++++++++
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/amsbr/OctoPrint-Stats/archive/v3.1.2.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/amsbr/OctoPrint-Stats/archive/v3.1.2.zip
ERROR: HTTP error 404 while getting https://github.com/amsbr/OctoPrint-Stats/archive/v3.1.2.zip
ERROR: Could not install requirement https://github.com/amsbr/OctoPrint-Stats/archive/v3.1.2.zip because of error 404 Client Error: Not Found for url: https://codeload.github.com/amsbr/OctoPrint-Stats/zip/v3.1.2
ERROR: Could not install requirement https://github.com/amsbr/OctoPrint-Stats/archive/v3.1.2.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/amsbr/OctoPrint-Stats/zip/v3.1.2 for URL https://github.com/amsbr/OctoPrint-Stats/archive/v3.1.2.zip
The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.

**Comment by AlexVerrico** [comment]
Hi @bgiovanny
Have you tried uninstalling and reinstalling the plugin?
Cheers, Alex.

**Comment by bgiovanny** [comment]
> Hi @bgiovanny
> Have you tried uninstalling and reinstalling the plugin?
> Cheers, Alex.

Yes, I tried and nothing 

> Hi @bgiovanny
> Have you tried uninstalling and reinstalling the plugin?
> Cheers, Alex.

yes:

Installing plugin from uploaded archive...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpNPHA0K.tar.gz --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpNPHA0K.tar.gz
ERROR: Package 'OctoPrint-Stats' requires a different Python: 2.7.16 not in '>=3.6,<4'
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by bgiovanny** [comment]
> Hi @bgiovanny
> Have you tried uninstalling and reinstalling the plugin?
> Cheers, Alex.

yes, I downloaded the files from here and:
Installing plugin from uploaded archive...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpmbZcyg.tar.gz --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpmbZcyg.tar.gz
ERROR: Package 'OctoPrint-Stats' requires a different Python: 2.7.16 not in '>=3.6,<4'
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by AlexVerrico** [comment]
Hi @bgiovanny 
The latest version of this plugin dropped support for python 2. It is recommended to upgrade from python 2 to python 3 for octoprint, you can find instructions for doing so here: https://octoprint.org/blog/2020/09/10/upgrade-to-py3/
If you cannot upgrade to python 3, please see the python 2 specific instructions in the readme.
Cheers, Alex.

**Comment by bgiovanny** [comment]
> Hi @bgiovanny
> The latest version of this plugin dropped support for python 2. It is recommended to upgrade from python 2 to python 3 for octoprint, you can find instructions for doing so here: https://octoprint.org/blog/2020/09/10/upgrade-to-py3/
> If you cannot upgrade to python 3, please see the python 2 specific instructions in the readme.
> Cheers, Alex.

I already installed python 3 and the last version of octopy the 1.5.2...

**Comment by bgiovanny** [comment]
> Hi @bgiovanny
> The latest version of this plugin dropped support for python 2. It is recommended to upgrade from python 2 to python 3 for octoprint, you can find instructions for doing so here: https://octoprint.org/blog/2020/09/10/upgrade-to-py3/
> If you cannot upgrade to python 3, please see the python 2 specific instructions in the readme.
> Cheers, Alex.

tks for your help
