### ISSUE TITLE
automated uninstall?

### ISSUE THREAD

**Issue by mlkoch** [AlexVerrico/octoprint-stats#23]
I have a problem with the automated installer in octoprint. The plugin is installed und uninstalled in one step:
Here is the log:
...
Successfully built OctoPrint-Stats
Installing collected packages: OctoPrint-Stats
Attempting uninstall: OctoPrint-Stats
Found existing installation: OctoPrint-Stats 3.1.2
Uninstalling OctoPrint-Stats-3.1.2:
Successfully uninstalled OctoPrint-Stats-3.1.2
Successfully installed OctoPrint-Stats-3.1.2
Fertig!
What do I do wrong?

**Comment by mlkoch** [comment]
~/oprint/bin/pip install "https://github.com/AlexVerrico/octoprint-stats/archive/master.zip"
works!

**Comment by AlexVerrico** [comment]
G'Day @mlkoch 
Are you attempting to install through the web interface or manually using the command line?
Cheers, Alex.

**Comment by mlkoch** [comment]
Installation inside octoprint was not successful. Installation in bash did work.

**Comment by AlexVerrico** [comment]
G'Day @mlkoch 
Can you please provide some more info such as: 
 - Octoprint Version: [eg. 1.4.0]
 - Browser: [e.g. chrome, safari]
 - Python Version: [eg. Python 3.8]
 - Operating system that Octoprint is running on: [eg. Debian 10.5, Windows 10]

Cheers, Alex.

**Comment by AlexVerrico** [comment]
This issue will be closed in 1 week due to inactivity
