### ISSUE TITLE
cant install the plugin

### ISSUE THREAD

**Issue by Flow2105** [AlexVerrico/octoprint-stats#24]
when i try to install it it takes a few minutes and then commes this
Fehler!
Could not install plugin, unknown error, please consult octoprint.log for details

how do i upload the log

**Comment by AlexVerrico** [comment]
G'Day @Flow2105 
Please read this and then upload your log files: https://community.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299
Cheers, Alex.

**Comment by AlexVerrico** [comment]
The specific logs that I need are the plugin manager logs and the general log

**Comment by Flow2105** [comment]
[serial.log.2021-01-10_09-17-26.zip](https://github.com/AlexVerrico/octoprint-stats/files/5824870/serial.log.2021-01-10_09-17-26.zip)

**Comment by AlexVerrico** [comment]
G'Day @Flow2105 
Can you please post the log files `octoprint.log` and `plugin_pluginmanager_console.log`
The serial log has nothing to do with this issue.
Cheers, Alex.

**Comment by Flow2105** [comment]
Now i anabled the serial.log and tryed it again two times now it was installed 
Thanks for your Support 👍 💯
