### ISSUE TITLE
Installation takes long and fails 

### ISSUE THREAD

**Issue by flaschetelefon** [AlexVerrico/octoprint-stats#3]
I have tried to install the plugin on my system using the plugin manager. It starts everything normally up to the following lines:

09:57:07,251 > Created wheel for OctoPrint-Stats: filename=OctoPrint_Stats-3.0.0-cp27-none-any.whl size=870602 sha256=2425fa48454ccc8040e48b122aa4bbc57c214fb37206320866a3c60a0c8465f9
09:57:07,251 > Stored in directory: /tmp/pip-ephem-wheel-cache-5g5B3A/wheels/9b/93/b7/53ddec31768b672a3665bf261b8a0c5ec18da892572fe8a53d
09:57:07,252 > Building wheel for pandas (setup.py): started
09:58:40,339 > Building wheel for pandas (setup.py): still running...
10:05:28,657 > Building wheel for pandas (setup.py): still running...
10:17:14,334 > Building wheel for pandas (setup.py): still running...
10:18:28,686 > Building wheel for pandas (setup.py): still running...

After that, I get the message that the installation failed.  The whole system is then unusable and must be restarted via the terminal. I have already updated and upgraded the RaspberryPi via the terminal. Also the third attempt to install the plugin was not successful.  To find the problems I have added the log's

I hope you can solve the problem

[octoprint_1.log](https://github.com/AlexVerrico/octoprint-stats/files/5421710/octoprint_1.log)
[plugin_pluginmanager_console_1.log](https://github.com/AlexVerrico/octoprint-stats/files/5421712/plugin_pluginmanager_console_1.log)

**Comment by AlexVerrico** [comment]
Hi @flaschetelefon 
Can you please post a list of any other plugins that you have installed?
Cheers,
Alex.

**Comment by danielrosero** [comment]
> Hi @flaschetelefon
> Can you please post a list of any other plugins that you have installed?
> Cheers,
> Alex.

Hi!. I'm facing the same issue. 

My plugin list is:

- Action Command Notification 
- Action Command Prompt Support
- Announcement Plugin
- Anonymous Usage Tracking
- Application Keys Plugin
- Backup & Restore
- Core Wizard
- Discovery
- Error Tracking
- File Check (2020.8.7)
- Firmware Check (2020.9.23)
- GCode Viewer 
- Logging
- Pi Support Plugin
- Software Update
- Telegram Notifications (1.6.0)
- Virtual Printer
- Webcam Iframe (0.0.4)

**Comment by flaschetelefon** [comment]
Thanks for your response.
My plugins are:
Bed Leveling Plugin (2.1.1)
Bed Visualizer (0.1.15)
FileManager (0.1.4)
PrintTimeGenius Plugin (2.2.6)
Telegram Notifications (1.6.0)

I have sorted them by 3rd party plugins.

**Comment by AlexVerrico** [comment]
Hi @flaschetelefon 
I have been unable to reproduce this issue on any of my dev machines.
Can you please try running the following command from the command line on your pi, and then post the file `pip_verbose.txt`: `/home/pi/oprint/bin/python2 -m pip install -v https://github.com/AlexVerrico/octoprint-stats/archive/master.zip >> pip_verbose.txt`
Cheers, 
Alex.

**Comment by flaschetelefon** [comment]
Hi @AlexVerrico 
I run the command. It took some time (about 30 min). The plugin was successfully installed and is already running. I have installed pip before (sudo apt install python-pip). No idea if this helped. 
Thanks for your quick support.

LG, Lukas
[pip_verbose.txt](https://github.com/AlexVerrico/octoprint-stats/files/5432940/pip_verbose.txt)

**Comment by skimaniac** [comment]
Same probleme here, the install fail with the following message: RuntimeError: Python version >= 3.6 required

**Comment by AlexVerrico** [comment]
@flaschetelefon good to know it worked.
@skimaniac that is a completely different problem. Please open a new issue if you need help solving it.
Cheers,
Alex.
